### ISSUE TITLE
(Presentation) Nice work!

### ISSUE THREAD

**Issue by CharlesDLandau** [msu11y/Codecademy.Biodiversity#2]
I enjoyed your presentation - it checks all the boxes, it's visually appealing and it comes to the correct conclusions. I only had a few notes:

- Excellent use of color scheme.
- Try to balance text with graphics as much as possible.
- I'm only familiar with using `::` to mean "as" so I was a bit thrown off by your use of it
- Check for typos and grammar
- Concluding "thank you" slides are always nice

Again, nice work and congratulations on finishing the class!

**Comment by msu11y** [comment]
Thanks for feedback! I had no idea :: even meant something...I always just used it for breaking up titles!

**Comment by msu11y** [comment]
What grammar/typos did you see?

**Comment by CharlesDLandau** [comment]
For example "heirin" on slide # 2. No need to go back and review, just advising for future presentations.
